In [9]:
import pandas as pd

price = pd.read_csv("../data/raw/sk_hynix_price.csv")
kospi = pd.read_csv("../data/raw/kospi.csv")

print(price.shape,kospi.shape)
price.head()

(135, 7) (135, 11)

         Date    Open    High     Low   Close   Volume    Change
0  2026-01-02  651000  679000  647000  677000  4181895  0.039939
1  2026-01-05  698000  700000  684000  696000  4337511  0.028065
2  2026-01-06  690000  727000  671000  726000  4830275  0.043103
3  2026-01-07  760000  762000  728000  742000  5693115  0.022039
4  2026-01-08  731000  788000  731000  756000  6496379  0.018868

In [6]:
price.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135 entries, 0 to 134
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    135 non-null    object
 1   Open    135 non-null    int64
 2   High    135 non-null    int64
 3   Low     135 non-null    int64
 4   Close   135 non-null    int64
 5   Volume  135 non-null    int64
 6   Change  135 non-null    float64
dtypes: float64(1), int64(5), object(1)
memory usage: 7.5+ KB

In [8]:
kospi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135 entries, 0 to 134
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    135 non-null    object
 1   Close   135 non-null    float64
 2   UpDown  135 non-null    int64
 3   Comp    135 non-null    float64
 4   Change  135 non-null    float64
 5   Open    135 non-null    float64
 6   High    135 non-null    float64
 7   Low     135 non-null    float64
 8   Volume  135 non-null    int64
 9   Amount  135 non-null    int64
 10  MarCap  135 non-null    int64
dtypes: float64(6), int64(4), object(1)
memory usage: 11.7+ KB

In [13]:
price['Date'] = pd.to_datetime(price['Date'])
kospi['Date'] = pd.to_datetime(kospi['Date'])

print(price['Date'].dtype)

datetime64[ns]

In [17]:
print(price.isna().sum())
print(kospi.isna().sum())

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
Change    0
dtype: int64
Date      0
Close     0
UpDown    0
Comp      0
Change    0
Open      0
High      0
Low       0
Volume    0
Amount    0
MarCap    0
dtype: int64

In [20]:
print(price['Date'].duplicated().sum())
print(kospi['Date'].duplicated().sum())

0
0

In [22]:
print(price['Date'].is_monotonic_increasing)
print(kospi['Date'].is_monotonic_increasing)

True
True

In [28]:
price['daily_return'] = price['Close'].pct_change() * 100 #how much percentage it has risen
price[['Date','Close','daily_return']].head(10) #why double bracket?

        Date   Close  daily_return
0 2026-01-02  677000           NaN
1 2026-01-05  696000      2.806499
2 2026-01-06  726000      4.310345
3 2026-01-07  742000      2.203857
4 2026-01-08  756000      1.886792
5 2026-01-09  744000     -1.587302
6 2026-01-12  749000      0.672043
7 2026-01-13  738000     -1.468625
8 2026-01-14  742000      0.542005
9 2026-01-15  749000      0.943396

In [26]:
price.nlargest(10, 'daily_return')[['Date','Close','daily_return']] #10 largest 
price.nsmallest(10, 'daily_return')[['Date','Close','daily_return']] #10 smallest

          Date    Close  daily_return
128 2026-07-13  1845000    -15.366972
121 2026-07-02  2187000    -14.570313
114 2026-06-23  2555000    -12.470024
131 2026-07-16  1842000    -11.527378
38  2026-03-03   939000    -11.498586
102 2026-06-05  2070000     -9.921671
39  2026-03-04   849000     -9.584665
42  2026-03-09   836000     -9.523810
21  2026-02-02   830000     -8.690869
117 2026-06-26  2673000     -8.364758

In [29]:
kospi['daily_return'] = kospi['Close'].pct_change() * 100 #how much percentage it has risen
kospi[['Date','Close','daily_return']].head(10) #why double bracket?

        Date    Close  daily_return
0 2026-01-02  4309.63           NaN
1 2026-01-05  4457.52      3.431617
2 2026-01-06  4525.48      1.524615
3 2026-01-07  4551.06      0.565244
4 2026-01-08  4552.37      0.028785
5 2026-01-09  4586.32      0.745765
6 2026-01-12  4624.79      0.838799
7 2026-01-13  4692.64      1.467094
8 2026-01-14  4723.10      0.649102
9 2026-01-15  4797.55      1.576295

In [30]:
kospi.nlargest(10, 'daily_return')[['Date','Close','daily_return']] #10 largest 
kospi.nsmallest(10, 'daily_return')[['Date','Close','daily_return']] #10 smallest

          Date    Close  daily_return
39  2026-03-04  5093.54    -12.057680
114 2026-06-23  8203.84     -9.991826
128 2026-07-13  6806.93     -8.948841
103 2026-06-08  7484.41     -8.285921
121 2026-07-02  7648.09     -7.892179
38  2026-03-03  5791.91     -7.242322
52  2026-03-23  5405.75     -6.494326
131 2026-07-16  6820.60     -6.367159
89  2026-05-15  7493.18     -6.117090
42  2026-03-09  5251.87     -5.962538

In [31]:
price.to_csv("../data/processed/sk_hynix_price_clean.csv", index = False)
kospi.to_csv("../data/processed/kospi_clean.csv", index = False)